name: zendesk_sdk
description: A Flutter plugin that integrates Zendesk Messaging SDK for Android and iOS.
version: 1.0.0+1

homepage: https://github.com/vishalsharma-hovr/zendesk_sdk
repository: https://github.com/vishalsharma-hovr/zendesk_sdk
issue_tracker: https://github.com/vishalsharma-hovr/zendesk_sdk/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.zendesk_sdk
        pluginClass: ZendeskSdkPlugin
      ios:
        pluginClass: ZendeskSdkPlugin
