package com.example.zendesk_sdk

object ZendeskSdkErrorCodes {
    const val INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    const val NO_UI_CONTEXT = "NO_UI_CONTEXT"
    const val NOT_INITIALIZED = "NOT_INITIALIZED"
    const val INIT_FAILED = "INIT_FAILED"
    const val CHAT_INIT_FAILED = "CHAT_INIT_FAILED"
    const val CHAT_ENGINE_FAILED = "CHAT_ENGINE_FAILED"
    const val LAUNCH_FAILED = "LAUNCH_FAILED"
    const val ANSWERBOT_ERROR = "ANSWERBOT_ERROR"
    const val LOGOUT_FAILED = "LOGOUT_FAILED"
    const val UNREAD_COUNT_FAILED = "UNREAD_COUNT_FAILED"
    const val PUSH_TOKEN_FAILED = "PUSH_TOKEN_FAILED"
    const val PUSH_NOTIFICATION_FAILED = "PUSH_NOTIFICATION_FAILED"
}
